spring:
  profiles:
    active: dev


---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.196.17:3306/permission?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
  redis:
    host: 106.15.196.17
    port: 6379
    database: 0
    password: root

#log
logging:
  level:
    com.wuyong.*: debug

#mybatis
#1.application 配置MapperScan
#2.yml文件配置属性
mybatis:
  type-aliases-package: com.wuyong.permission.model
  mapper-locations: classpath:mapper/*.xml



---
spring:
  profiles: prod